# version: '3.8'
# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     environment:
#       - NODE_ENV=production
#       - PORT=8000
#       - FASTAPI_URL=http://ml_service:8000
#       - MONGODB_URI=${MONGODB_URI}
#     depends_on:
#       - ml_service
#     volumes:
#       - ./backend/uploads:/app/uploads

#   ml_service:
#     build:
#       context: ./ml_service
#       dockerfile: Dockerfile
#     ports:
#       - "8001:8000"
#     environment:
#       - PYTHONUNBUFFERED=1
#     volumes:
#       - ./ml_service/models:/app/models