// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEqnpRV8s7YV0oAZIVzgYjTAgLPbZB8kY',
    appId: '1:970958422401:web:acfecfdebf31a7a2c9e880',
    messagingSenderId: '970958422401',
    projectId: 'sigma-8d395',
    authDomain: 'sigma-8d395.firebaseapp.com',
    storageBucket: 'sigma-8d395.firebasestorage.app',
    measurementId: 'G-DMWRQYS73B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGf4ipFb5JGA2uMDq_1S-NeMUvxEoSY7I',
    appId: '1:970958422401:android:375c231a768165c7c9e880',
    messagingSenderId: '970958422401',
    projectId: 'sigma-8d395',
    storageBucket: 'sigma-8d395.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR0vzWjrPHW1h2jmrNq_Zygn6foqxXOQs',
    appId: '1:970958422401:ios:5df9a1200be17066c9e880',
    messagingSenderId: '970958422401',
    projectId: 'sigma-8d395',
    storageBucket: 'sigma-8d395.firebasestorage.app',
    iosBundleId: 'com.example.sigma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR0vzWjrPHW1h2jmrNq_Zygn6foqxXOQs',
    appId: '1:970958422401:ios:5df9a1200be17066c9e880',
    messagingSenderId: '970958422401',
    projectId: 'sigma-8d395',
    storageBucket: 'sigma-8d395.firebasestorage.app',
    iosBundleId: 'com.example.sigma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEqnpRV8s7YV0oAZIVzgYjTAgLPbZB8kY',
    appId: '1:970958422401:web:2fe30709ce1b43f1c9e880',
    messagingSenderId: '970958422401',
    projectId: 'sigma-8d395',
    authDomain: 'sigma-8d395.firebaseapp.com',
    storageBucket: 'sigma-8d395.firebasestorage.app',
    measurementId: 'G-2F6QQY1DKB',
  );
}
